server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  devtools:
    restart:
      additional-paths: src/main/resources/public
  datasource:
    initialize: false
    password: password
    url: jdbc:postgresql://ec2-3-110-197-20.ap-south-1.compute.amazonaws.com:5432/szozat
    username: postgres
  jpa:
    hibernate:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
    show-sql: true
    generate-ddl: true
